services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DB: bdxdb
      MYSQL_USER: bdxadmin
      MYSQL_PASSWORD: OsjQusnq880Uqs
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

volumes:
  db_data:
